
function dataReader(){

  // check file format (endings and headers)

  // do the right reader

}

function vtk_reader(){

  /*# vtk DataFile Version 2.0
  generated by FAnToM ( VTK/Save )
  BINARY
  DATASET STRUCTURED_GRID
  DIMENSIONS 1415 979 1
  POINTS 1385285 double*/



}


function vtk_XML_reader(){

  
}
