
function vtk_reader(content){

  /*# vtk DataFile Version 2.0
  generated by FAnToM ( VTK/Save )
  BINARY
  DATASET STRUCTURED_GRID
  DIMENSIONS 1415 979 1
  POINTS 1385285 double*/


  console.log(content);



}


function vtk_XML_reader(){


}
